import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>marcless.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        product detail page {router.query.handle}
      </>
    </>
  )
}


export default Home
