import type { NextPage } from 'next';
import Head from 'next/head';
import HeroWithProduct from '@/src/components/HeroProduct';
import FeatureList from '@/src/components/FeatureList';
import Banner from '@/src/components/Banner';
import ContentMedia from '@/src/components/ContentMedia';
import ProductGrid from '@/src/components/ProductGrid';
import FeaturedProduct from '@/src/components/FeaturedProduct';
import TestimonialGrid from '@/src/components/TestimonialGrid';
import Button from '@/src/components/Button';
import { GetProducts, GetProductsVariables, PRODUCTS_QUERY } from '../queries';
import client from '../utils/apollo';
import manShaving from '@/src/assets/man-shaving.jpeg';
import womanShaving from '@/src/assets/woman-shaving.jpg';

const Home: NextPage<GetProducts> = ({ products }) => {
  return (
    <>
      <Head>
        <title>marcless.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <HeroWithProduct />
        <FeatureList />
        <FeaturedProduct product={products.edges[0].node} />
        {/* <ProductGrid products={products}/> */}
        <Banner
          heading="High-performance products for personal grooming."
          image={womanShaving}
        />
        {/* <ContentMedia
          heading="Your closest shave yet!"
          body="Sustainable, luxury safety razors eliminate razor burn and ingrown hairs for your closest shave yet! They are suitable for men, women and anyone in-between and outside of that. Switching to a safety razor will save you hundreds of dollars in the long run!"
          image={manShaving}
          cta={
            <Button href="/shop" variant="primary">
              shop
            </Button>
          }
        /> */}
        <TestimonialGrid />
      </>
    </>
  )
}

export const getStaticProps = async () => {
  const { data } = await client.query<GetProducts, GetProductsVariables>({
    query: PRODUCTS_QUERY,
    variables: {
      first: 2,
    }
  });

  return {
    props: {
      ...data
    },
  }
}

export default Home
