import type { NextPage } from 'next';
import Head from 'next/head';
import { useContext, useState } from 'react';
import { ShieldCheckIcon, CashIcon, CheckIcon } from '@heroicons/react/outline';
import HeroWithProduct from '@/src/components/HeroProduct';
import FeatureList from '@/src/components/FeatureList';
import Banner from '@/src/components/Banner';
import ContentMedia from '@/src/components/ContentMedia';
import TestimonialGrid from '@/src/components/TestimonialGrid';
import Button from '@/src/components/Button';
import NewsletterForm from '@/src/components/NewsletterForm';
import { GetProducts, GetProductsVariables, PRODUCTS_QUERY } from '@/src/queries';
import client from '@/src/utils/apollo';
import { Context } from '@/src/state';
import womanShaving from '@/src/assets/woman-shaving.jpg';
import brightSilverInStand from '@/src/assets/bright-silver-in-stand.jpg';
import goldWhiteOnDish from '@/src/assets/gold-white-on-dish.jpg';

const Home: NextPage<GetProducts> = ({ products }) => {
  const { state: { active }, dispatch } = useContext(Context);
  const [signupSuccess, setSignupSuccess] = useState(false);

  if (!active) {
    return (
      <>
        <Head>
          <title>marcless.com</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <section className="h-screen w-screen flex items-center">
          <div className="container mx-auto flex flex-col items-center">
            <div>
              <h1 className="font-serif block text-8xl tracking-wide mb-1">
                marc<span className="bg-primary text-white">less</span>
              </h1>
              <h2 className="text-base">Better stuff, fewer dollars.</h2>
            </div>
            <div className="mt-12 flex flex-col justify-center items-center">
              {signupSuccess ? (
                <p>Thank you for signing up!</p>
              ) : (
                <>
                  <p className="mb-4">Enter your email below to get notified when we go live.</p>
                  <NewsletterForm
                    centered
                    onSubmitForm={() => setSignupSuccess(true)}
                  />
                </>
              )}
            </div>
          </div>
        </section>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>marcless.com</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <>
        <HeroWithProduct />
        <ContentMedia
          eyebrow="irreplaceable"
          heading="Made for a lifetime"
          body="Most razors you'll find today are designed to be replaced. The Marc Razor is sustainable, made from clean materials that last."
          image={brightSilverInStand}
          cta={
            <Button href="/shop" variant="primary">
              shop razors
            </Button>
          }
        />

        <FeatureList
          eyebrow="why marc<i>less</i>"
          heading="Say good bye to the <b>BrandTax™</b>."
          body="We’ve created a thoughtful selection of quality razors and shaving accessories you reach for every day."
          items={[
            {
              name: 'Affordability',
              description:
                'Better stuff, fewer dollars. It’s that simple.',
              icon: CashIcon,
            },
            {
              name: 'Quality',
              description:
                'Built from the highest quality materials in the industry.',
              icon: CheckIcon,
            },
            {
              name: 'Clean and sustainable',
              description:
                'Durable and recyclable, while free of nasty chemicals.',
              icon: ShieldCheckIcon,
            },
          ]}
        />

        <ContentMedia
          imagePosition="left"
          eyebrow="just a better shave"
          heading="Say goodbye to irritation, nicks, and bumps"
          body="More is not always good. Say goodbye to the 3+ blades Big Razor companies are telling you to buy. One blade is truly all you need. No more irritation, nicks, or red bumps."
          image={womanShaving}
          cta={
            <Button href="/shop" variant="primary">
              shop razors
            </Button>
          }
        />

        <TestimonialGrid />

        <Banner
          heading="Guaranteed to eliminate cuts, nicks, and irritation."
          image={goldWhiteOnDish}
          cta={
            <Button href="/shop" variant="primary">
              shop razors
            </Button>
          }
        />

        {/* <FeaturedProduct product={products.edges[0].node} /> */}
        {/* <ProductGrid products={products}/> */}
        {/* <Banner
          heading="High-performance products for personal grooming."
          image={womanShaving}
        /> */}
        {/* <ContentMedia
          heading="Your closest shave yet!"
          body="Sustainable, luxury safety razors eliminate razor burn and ingrown hairs for your closest shave yet! They are suitable for men, women and anyone in-between and outside of that. Switching to a safety razor will save you hundreds of dollars in the long run!"
          image={manShaving}
          cta={
            <Button href="/shop" variant="primary">
              shop
            </Button>
          }
        /> */}

        <div className="my-24"></div>
      </>
    </>
  )
}

export const getStaticProps = async () => {
  const { data } = await client.query<GetProducts, GetProductsVariables>({
    query: PRODUCTS_QUERY,
    variables: {
      first: 2,
    }
  });

  return {
    props: {
      ...data
    },
  }
}

export default Home
